/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx,js,jsx}', './docs/**/*.{md,mdx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#e3e2e2',
        'inverse-surface': '#e2e2e2',
        'on-error-container': '#ffdad6',
        primary: '#ffffff',
        'on-primary': '#1a1c1c',
        'inverse-on-surface': '#303030',
        'on-secondary-fixed-variant': '#3a3c3c',
        'tertiary-fixed': '#5e5e5e',
        'on-tertiary': '#1b1c1c',
        'tertiary-container': '#919191',
        error: '#ffb4ab',
        tertiary: '#e3e2e2',
        'primary-container': '#d4d4d4',
        'secondary-fixed-dim': '#aaabab',
        'surface-container-high': '#2a2a2a',
        'on-tertiary-container': '#000000',
        'on-secondary': '#1a1c1c',
        'on-secondary-container': '#e2e2e2',
        'on-error': '#690005',
        'surface-container': '#1f1f1f',
        'on-primary-fixed': '#ffffff',
        'on-primary-container': '#000000',
        'secondary-container': '#454747',
        secondary: '#c6c6c7',
        'on-primary-fixed-variant': '#e2e2e2',
        'surface-container-highest': '#353535',
        'surface-tint': '#c6c6c7',
        'primary-fixed': '#5d5f5f',
        'on-surface': '#e2e2e2',
        'error-container': '#93000a',
        'outline-variant': '#474747',
        'on-background': '#e2e2e2',
        outline: '#919191',
        'on-secondary-fixed': '#1a1c1c',
        'surface-dim': '#131313',
        'on-tertiary-fixed': '#ffffff',
        'surface-container-lowest': '#0e0e0e',
        'on-surface-variant': '#c6c6c6',
        background: '#131313',
        'inverse-primary': '#5d5f5f',
        surface: '#131313',
        'surface-bright': '#393939',
        'secondary-fixed': '#c6c6c7',
        'primary-fixed-dim': '#454747',
        'surface-variant': '#353535',
        'surface-container-low': '#1b1b1b',
        'tertiary-fixed-dim': '#464747',
      },
      fontFamily: {
        headline: ['Space Grotesk'],
        body: ['Space Grotesk'],
        label: ['Space Grotesk'],
      },
      borderRadius: { DEFAULT: '0px', lg: '0px', xl: '0px', full: '9999px' },
    },
  },
  corePlugins: {
    preflight: false,
  },
}
